#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-Sen-TH" id="HB-UNI-Sen-TH">
DEVICE="HB-UNI-Sen-CO2"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="Kohlendioxid-Sensor"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-uni-sen-co2.png
DEVICE_THUMB=hb-uni-sen-co2_thumb.png

#------------------------------------------------------------------------------
# Edit DEVDB.tcl
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE \"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Edit webui.js
webuiFile="/www/webui/webui.js"

webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"'$DEVICE'\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

# Insert channel config params
webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="HBWEATHER|CO2_CALIB_REF"
webuiInsertValue="stringTableHBWeatherCo2CalibRef"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HBWEATHER|CO2_LEVEL_AMBER"
webuiInsertValue="stringTableHBWeatherCo2LevelAmber"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HBWEATHER|CO2_LEVEL_RED"
webuiInsertValue="stringTableHBWeatherCo2LevelRed"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HBWEATHER|CO2_LEVEL_NO_GREEN"
webuiInsertValue="stringTableHBWeatherCo2LevelNoGreen"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

#------------------------------------------------------------------------------
### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="HBWEATHER|CO2\t\${stringTableHBWeatherCO2}"
if [ -z "`cat $stringtable_deFile | grep \"HBWEATHER|CO2"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HBWEATHER|AIR_PRESSURE\t\${stringTableHBWeatherAirPressure}"
if [ -z "`cat $stringtable_deFile | grep \"HBWEATHER|AIR_PRESSURE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HBWEATHER|CO2_CALIB_REF\t\${stringTableHBWeatherCo2CalibRef}"
if [ -z "`cat $stringtable_deFile | grep \"HBWEATHER|CO2_CALIB_REF"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HBWEATHER|CO2_LEVEL_AMBER\t\${stringTableHBWeatherCo2LevelAmber}"
if [ -z "`cat $stringtable_deFile | grep \"HBWEATHER|CO2_LEVEL_AMBER"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HBWEATHER|CO2_LEVEL_RED\t\${stringTableHBWeatherCo2LevelRed}"
if [ -z "`cat $stringtable_deFile | grep \"HBWEATHER|CO2_LEVEL_RED"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HBWEATHER|CO2_LEVEL_NO_GREEN\t\${stringTableHBWeatherCo2LevelNoGreen}"
if [ -z "`cat $stringtable_deFile | grep \"HBWEATHER|CO2_LEVEL_NO_GREEN"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi


#------------------------------------------------------------------------------
### Edit German translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHBWeatherCO2\" : \"Kohlendioxid\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBWeatherCO2\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBWeatherAirPressure\" : \"Luftdruck\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBWeatherAirPressure\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBWeatherCo2CalibRef\" : \"Kalibrierungswert\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBWeatherCo2CalibRef\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBWeatherCo2LevelAmber\" : \"Ampelschwelle Gelb\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBWeatherCo2LevelAmber\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBWeatherCo2LevelRed\" : \"Ampelschwelle Rot\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBWeatherCo2LevelRed\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBWeatherCo2LevelNoGreen\" : \"Gr%FCne Ampel ausblenden\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBWeatherCo2LevelNoGreen\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

#------------------------------------------------------------------------------
### Edit English translate.lang.stringtable.js ###
translate_enFile="/www/webui/js/lang/en/translate.lang.stringtable.js"
translate_enSearch="\"dummy\" : \"\","

translate_enInsert="\n    \"stringTableHBWeatherCO2\" : \"Carbondioxide\","
if [ -z "`cat $translate_enFile | grep \"stringTableHBWeatherCO2\"`" ]; then
	sed -i "s/\($translate_enSearch\)/\1$translate_enInsert/g" $translate_enFile
fi

translate_enInsert="\n    \"stringTableHBWeatherAirPressure\" : \"Air Pressure\","
if [ -z "`cat $translate_enFile | grep \"stringTableHBWeatherAirPressure\"`" ]; then
	sed -i "s/\($translate_enSearch\)/\1$translate_enInsert/g" $translate_enFile
fi

translate_enInsert="\n    \"stringTableHBWeatherCo2CalibRef\" : \"Calibration Value\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBWeatherCo2CalibRef\"`" ]; then
	sed -i "s/\($translate_enSearch\)/\1$translate_enInsert/g" $translate_enFile
fi

translate_enInsert="\n    \"stringTableHBWeatherCo2LevelAmber\" : \"Traffic Light Level Amber\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBWeatherCo2LevelAmber\"`" ]; then
	sed -i "s/\($translate_enSearch\)/\1$translate_enInsert/g" $translate_enFile
fi

translate_enInsert="\n    \"stringTableHBWeatherCo2LevelRed\" : \"Traffic Light Level Red\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBWeatherCo2LevelRed\"`" ]; then
	sed -i "s/\($translate_enSearch\)/\1$translate_enInsert/g" $translate_enFile
fi

translate_enInsert="\n    \"stringTableHBWeatherCo2LevelNoGreen\" : \"Disable Green Traffic Light\","
if [ -z "`cat $translate_enFile | grep \"stringTableHBWeatherCo2LevelNoGreen\"`" ]; then
	sed -i "s/\($translate_enSearch\)/\1$translate_enInsert/g" $translate_enFile
fi
