#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-Sen-TH" id="HB-UNI-Sen-TH">
DEVICE="HB-UNI-Sen-S0-E"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="S0-Energiezaehler"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-uni-sen-s0-e.png
DEVICE_THUMB=hb-uni-sen-s0-e_thumb.png


#------------------------------------------------------------------------------
# Edit DEVDB.tcl
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "


if [ -z "`cat $devdescrFile | grep \"$DEVICE \"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Edit webui.js
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"'$DEVICE'\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

# Insert channel config params
webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="HBWEATHER|USE_OFFSET"
webuiInsertValue="stringTableHBWeatherUseOffset"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="HBWEATHER|WH_OFFSET"
webuiInsertValue="stringTableHBWeatherWhOffset"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

#------------------------------------------------------------------------------
### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="HBWEATHER|E_ENERGY_COUNTER\t\${stringTableHBWeatherE_Energy_Counter}"
if [ -z "`cat $stringtable_deFile | grep \"HBWEATHER|E_ENERGY_COUNTER"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HBWEATHER|CURRENT_POWER\t\${stringTableHBWeatherCurrentPower}"
if [ -z "`cat $stringtable_deFile | grep \"HBWEATHER|CURRENT_POWER"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HBWEATHER|USE_OFFSET\t\${stringTableHBWeatherUseOffset}"
if [ -z "`cat $stringtable_deFile | grep \"HBWEATHER|USE_OFFSET"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="HBWEATHER|WH_OFFSET\t\${stringTableHBWeatherWhOffset}"
if [ -z "`cat $stringtable_deFile | grep \"HBWEATHER|WH_OFFSET"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

#------------------------------------------------------------------------------
### Edit German translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHBWeatherE_Energy_Counter\" : \"Energiez%E4hler\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBWeatherE_Energy_Counter\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBWeatherCurrentPower\" : \"Aktuelle Leistung\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBWeatherCurrentPower\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBWeatherUseOffset\" : \"Start-Z%E4hlerstand %FCbernehmen\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBWeatherUseOffset\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableHBWeatherWhOffset\" : \"Start-Z%E4hlerstand\","
if [ -z "`cat $translate_deFile | grep \"stringTableHBWeatherWhOffset\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
