#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Geraetetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-Sen-TH" id="HB-UNI-Sen-TH">
DEVICE="HB-UNI-Sen-Sky"
# in der WebUI angezeigte Geraetebeschreibung
DEVICE_DESC="Helligkeits-UV-Himmelstemperatur-Sensor"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-uni-sen-sky.png
DEVICE_THUMB=hb-uni-sen-sky_thumb.png
#Name des xml files
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-sky.xml

#------------------------------------------------------------------------------
# Undo DEVDB.tcl changes
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ "`cat $devdescrFile | grep \"$DEVICE \"`" ]; then
        sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Undo webui.js changes
webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"'$DEVICE'\"`" ]; then
        sed -i "/\('$DEVICE'\)/d" $webuiFile
fi

#------------------------------------------------------------------------------
### undo stringtable_de.txt changes
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deSearch="HBWEATHER|SKY_TEMPERATURE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HBWEATHER|UV_INDEX"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HBWEATHER|LUX"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HBWEATHER|BATTERY_VOLTAGE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

#------------------------------------------------------------------------------
### undo German translate.lang.stringtable.js changes
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"

translate_deSearch="stringTableHBWeatherSkyTemperature"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBWeatherUvIndex"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBWeatherLux"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBWeatherBatteryVoltage"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

#------------------------------------------------------------------------------
### undo English translate.lang.stringtable.js changes
translate_enFile="/www/webui/js/lang/en/translate.lang.stringtable.js"

translate_enSearch="stringTableHBWeatherSkyTemperature"
sed -i "/\(${translate_enSearch}\)/d" $translate_enFile
translate_enSearch="stringTableHBWeatherUvIndex"
sed -i "/\(${translate_enSearch}\)/d" $translate_enFile
translate_enSearch="stringTableHBWeatherLux"
sed -i "/\(${translate_enSearch}\)/d" $translate_enFile
translate_enSearch="stringTableHBWeatherBatteryVoltage"
sed -i "/\(${translate_enSearch}\)/d" $translate_enFile

#------------------------------------------------------------------------------
# remove device_xml links
rm -f $FIRMWARE_FILE

#------------------------------------------------------------------------------
# remove image files
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
