#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-Sen-TH" id="HB-UNI-Sen-TH">
DEVICE="HB-UNI-Sen-IAQ"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="Luftgüte-Sensor"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-uni-sen-iaq.png
DEVICE_THUMB=hb-uni-sen-iaq_thumb.png
#Name des xml files
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-iaq.xml

#------------------------------------------------------------------------------
# Undo DEVDB.tcl changes
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ "`cat $devdescrFile | grep \"$DEVICE \"`" ]; then
        sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Undo webui.js changes
webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"'$DEVICE'\"`" ]; then
        sed -i "/\('$DEVICE'\)/d" $webuiFile
fi


#------------------------------------------------------------------------------
### undo stringtable_de.txt changes
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deSearch="HBWEATHER|TVOC"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HBWEATHER|IAQ"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

#------------------------------------------------------------------------------
### undo German translate.lang.stringtable.js changes
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"

translate_deSearch="stringTableHBWeatherTVOC"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHBWeatherIAQ"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHbIaqExcellent"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbIaqGood"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbIaqModerate"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbIaqPoor"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbIaqUnhealthy"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

#------------------------------------------------------------------------------
### undo English translate.lang.stringtable.js changes
translate_enFile="/www/webui/js/lang/en/translate.lang.stringtable.js"

translate_enSearch="stringTableHBWeatherTVOC"
sed -i "/\(${translate_enSearch}\)/d" $translate_enFile
translate_enSearch="stringTableHBWeatherIAQ"
sed -i "/\(${translate_enSearch}\)/d" $translate_enFile

translate_enSearch="stringTableHbIaqExcellent"
sed -i "/\(${translate_enSearch}\)/d" $translate_enFile
translate_enSearch="stringTableHbIaqGood"
sed -i "/\(${translate_enSearch}\)/d" $translate_enFile
translate_enSearch="stringTableHbIaqModerate"
sed -i "/\(${translate_enSearch}\)/d" $translate_enFile
translate_enSearch="stringTableHbIaqPoor"
sed -i "/\(${translate_enSearch}\)/d" $translate_enFile
translate_enSearch="stringTableHbIaqUnhealthy"
sed -i "/\(${translate_enSearch}\)/d" $translate_enFile

#------------------------------------------------------------------------------
# remove device_xml links
rm -f $FIRMWARE_FILE

#------------------------------------------------------------------------------
# remove image files
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
