#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter stringTableHBWeatherAirPressuretetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-Sen-TH" id="HB-UNI-Sen-TH">
DEVICE="HB-UNI-Sen-PM"
# in der WebUI angezeigte Geraetebeschreibung
DEVICE_DESC="Feinstaub-Sensor"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-uni-sen-pm.png
DEVICE_THUMB=hb-uni-sen-pm_thumb.png
#Name des xml files
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-pm.xml

#------------------------------------------------------------------------------
# Undo DEVDB.tcl changes
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ "`cat $devdescrFile | grep \"$DEVICE \"`" ]; then
        sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Undo webui.js changes
webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"'$DEVICE'\"`" ]; then
        sed -i "/\('$DEVICE'\)/d" $webuiFile
fi


#------------------------------------------------------------------------------
### undo stringtable_de.txt changes
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deSearch="HBWEATHER|PM_UPTODATE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|PM_UPTODATEfalse"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|PM_UPTODATEtrue"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|PM_1P0"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|PM_2P5"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|PM_4P0"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|PM_10P0"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|NC_0P5"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|NC_1P0"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|NC_2P5"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|NC_4P0"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|NC_10P0"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|AVG_PARTICLE_SIZE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

#------------------------------------------------------------------------------
### undo German translate.lang.stringtable.js changes
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"

translate_deSearch="stringTableHBWeatherPM_UPTODATE"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherPM_UPTODATEfalse"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherPM_UPTODATEtrue"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherPM_1P0"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherPM_2P%"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherPM_4P0"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherPM_10P0"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherNC_0P5"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherNC_1P0"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherNC_2P5"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherNC_4P0"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherNC_10P0"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherAvgParticleSize"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

#------------------------------------------------------------------------------
# remove device_xml links
rm -f $FIRMWARE_FILE

#------------------------------------------------------------------------------
# remove image files
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
