#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-Sen-TH" id="HB-UNI-Sen-TH">
DEVICE="HB-UNI-Sen-CAP-MOIST"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="Kapazitiver Bodenfeuchte-Sensor"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-uni-sen-cap-moist.png
DEVICE_THUMB=hb-uni-sen-cap-moist_thumb.png
#Name des xml files
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-cap-moist.xml

#------------------------------------------------------------------------------
# Undo DEVDB.tcl changes
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ "`cat $devdescrFile | grep \"$DEVICE \"`" ]; then
        sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Undo webui.js changes
webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"'$DEVICE'\"`" ]; then
        sed -i "/\('$DEVICE'\)/d" $webuiFile
fi

# remove channel/dev params
webuiSearch="TRANSMIT_INTERVAL"
sed -i "/\($webuiSearch\)/d" $webuiFile

webuiSearch="CAP_MOIST_HIGH_VALUE"
sed -i "/\($webuiSearch\)/d" $webuiFile

webuiSearch="CAP_MOIST_LOW_VALUE"
sed -i "/\($webuiSearch\)/d" $webuiFile

#------------------------------------------------------------------------------
### undo stringtable_de.txt changes
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deSearch="TRANSMIT_INTERVAL"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|BATTERY_VOLTAGE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|CAP_MOIST_HIGH_VALUE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|CAP_MOIST_LOW_VALUE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="HBWEATHER|MOISTURE"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

#------------------------------------------------------------------------------
### undo German translate.lang.stringtable.js changes
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"

translate_deSearch="stringTableTransmitInterval"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherBatteryVoltage"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherCapMoistHighValue"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherCapMoistLowValue"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableHBWeatherMoisture"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

#------------------------------------------------------------------------------
# remove device_xml links
rm -f $FIRMWARE_FILE

#------------------------------------------------------------------------------
# remove image files
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
